-- MySQL Script generated by SGA - Sistema de Gerenciamento de Apontamentos
-- 03/07/16 12:25:34
-- Model: Banco SGA    Version: 1.0
-- Responsável: Tárcio Lima

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sga
-- -----------------------------------------------------
-- Banco de Dados da aplicação SGA - Sistema de Gestão de Apontamentos

-- -----------------------------------------------------
-- Schema sga
--
-- Banco de Dados da aplicação SGA - Sistema de Gestão de Apontamentos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sga` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `sga` ;

-- -----------------------------------------------------
-- Table `sga`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nome_cargo` VARCHAR(45) NOT NULL,
  `permissao_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cargo`),
  UNIQUE INDEX `nome_cargo_UNIQUE` (`nome_cargo` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sga`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `nome_user` VARCHAR(45) NOT NULL,
  `email_user` VARCHAR(45) NOT NULL,
  `cargo_user` INT NULL,
  `senha_user` VARCHAR(45) NULL,
  `dt_create_user` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Data e hora da criação do usuário',
  `status_user` BIT(1) NOT NULL DEFAULT 1 COMMENT '0 = Inativo; 1 - Ativo',
  `codigo_user` VARCHAR(45) NOT NULL COMMENT 'chave de reset de senha',
  PRIMARY KEY (`id_user`, `cargo_user`),
  UNIQUE INDEX `email_user_UNIQUE` (`email_user` ASC),
  INDEX `fk_cargo_id_userx` (`cargo_user` ASC),
  CONSTRAINT `fk_cargo_user`
    FOREIGN KEY (`cargo_user`)
    REFERENCES `sga`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sga`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `nome_evento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_evento`),
  UNIQUE INDEX `nome_cargo_UNIQUE` (`nome_evento` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`gestor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`gestor` (
  `id_gestor` INT NOT NULL AUTO_INCREMENT,
  `nome_gestor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_gestor`),
  UNIQUE INDEX `nome_cargo_UNIQUE` (`nome_gestor` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sga`.`apontamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sga`.`apontamento` (
  `id_apontamento` INT NOT NULL AUTO_INCREMENT,
  `user_apontamento` INT NOT NULL,
  `data_apontamento` DATE NOT NULL,
  `hr_ini_apontamento` TIME NOT NULL,
  `hr_fim_apontamento` TIME NOT NULL,
  `site_apontamento` VARCHAR(45) NOT NULL,
  `os_apontamento` INT NULL,
  `evento_apontamento` INT NULL,
  `descricao_apontamento` VARCHAR(500) NOT NULL,
  `veiculo_apontamento` VARCHAR(45) NULL,
  `gestor_apontamento` INT NULL,
  `obs_apontamento` VARCHAR(500) NULL,
  `data_registro_apontamento` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Data e hora da criação do apontamento',
  PRIMARY KEY (`id_apontamento`, `gestor_apontamento`, `operadora_apontamento`, `evento_apontamento`, `user_apontamento`),
  UNIQUE INDEX `id_apontamento_UNIQUE` (`id_apontamento` ASC),
  INDEX `os_apontamento_idx` (`evento_apontamento` ASC),
  INDEX `os_apontamento_idx1` (`gestor_apontamento` ASC),
  INDEX `os_apontamento_idx2` (`user_apontamento` ASC),
  CONSTRAINT `fk_evento_apontamento`
    FOREIGN KEY (`evento_apontamento`)
    REFERENCES `sga`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gestor_apontamento`
    FOREIGN KEY (`gestor_apontamento`)
    REFERENCES `sga`.`gestor` (`id_gestor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `os_apontamento`
    FOREIGN KEY (`user_apontamento`)
    REFERENCES `sga`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for tables tha `sga`
-- -----------------------------------------------------
START TRANSACTION;
USE `sga`;
INSERT INTO `sga`.`cargo` (`nome_cargo`, `permissao_cargo`) VALUES ('Estagiário', 'Campo');
INSERT INTO `sga`.`cargo` (`nome_cargo`, `permissao_cargo`) VALUES ('Montador', 'Campo');
INSERT INTO `sga`.`cargo` (`nome_cargo`, `permissao_cargo`) VALUES ('Técnico', 'Campo');
INSERT INTO `sga`.`cargo` (`nome_cargo`, `permissao_cargo`) VALUES ('Projetista', 'Campo');
INSERT INTO `sga`.`cargo` (`nome_cargo`, `permissao_cargo`) VALUES ('Gestor', 'Gestao');
INSERT INTO `sga`.`cargo` (`nome_cargo`, `permissao_cargo`) VALUES ('Staff', 'Controller');
INSERT INTO `sga`.`cargo` (`nome_cargo`, `permissao_cargo`) VALUES ('Consulta', 'Consulta');
INSERT INTO `sga`.`cargo` (`nome_cargo`, `permissao_cargo`) VALUES ('Coordenador', 'Coordenador');
INSERT INTO `sga`.`cargo` (`id_cargo`, `nome_cargo`, `permissao_cargo`) VALUES ('100', 'Administrador', 'Root');

INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Aguardando atividades');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Improdutividade Ensel');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Improdutividade Cliente');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Deslocamento');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Vistoria');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Instalação');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Teste');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Aceitação');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Documentação');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('CGR');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Divisão de Turno');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Supervisão');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Compensação');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Atestado');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Falta');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Treinamento');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Intervalo de Almoço');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Intervalo de Janta');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Intervalo entre turnos');
INSERT INTO `sga`.`evento` (`nome_evento`) VALUES ('Descanso Remunerado');

INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('Anderson Luis');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('André Luis');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('Alex Diogo');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('Henrique Oliveira');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('Gerlan Taares');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('Pedro Gomes');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('Maro Lopes');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('Marcela Testi');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('Cláudio Figueiredo');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('Tárcio Lima');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('Michelle Antunes');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('Thiago Pessoa');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('Gerson Severino');
INSERT INTO `sga`.`gestor` (`nome_gestor`) VALUES ('José Márcio');

INSERT INTO `sga`.`user` (`nome_user`, `email_user`, `cargo_user`, `senha_user`) VALUES ('Tárcio Lima', 'tarcio@ensel.com.br', '100', MD5('123')); 
INSERT INTO `sga`.`user` (`nome_user`, `email_user`, `cargo_user`, `senha_user`) VALUES ('Maro Lopes', 'maro@ensel.com.br', '100', MD5('123'));

COMMIT;

